# Generated by Django 4.1.5 on 2023-01-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baza_ogloszen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=80)),
                ('lokalizacja', models.CharField(max_length=80)),
                ('cena', models.CharField(max_length=30)),
                ('cena_za_metr', models.CharField(max_length=30)),
                ('liczba_pokoi', models.CharField(max_length=30)),
                ('powierzchnia', models.CharField(max_length=20)),
                ('url_link', models.TextField(max_length=200)),
                ('data_wystawienia', models.DateTimeField()),
                ('data_zakonczenia', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
