# Generated by Django 4.1.5 on 2023-03-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='cena',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='cena_za_metr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='data_wystawienia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='liczba_pokoi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='lokalizacja',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='powierzchnia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='tytul',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='url_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
