# Generated by Django 4.1.5 on 2023-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_baza_ogloszen_cena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza_ogloszen',
            name='foto',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
