# Generated by Django 4.1.5 on 2023-03-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_baza_ogloszen_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='linki_otodom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul_linka', models.CharField(blank=True, max_length=80, null=True)),
                ('url_linka', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
