# Generated by Django 4.1.5 on 2023-03-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_test_aktywnosci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_aktywnosci',
            old_name='data_wystawienia',
            new_name='aktywnosc_skryptu',
        ),
    ]
