# Generated by Django 4.1.5 on 2023-03-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_rename_data_wystawienia_test_aktywnosci_aktywnosc_skryptu'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_aktywnosci',
            name='status_skryptu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
