# Generated by Django 4.1.5 on 2023-06-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_test_aktywnosci_status_skryptu'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza_ogloszen',
            name='ulubione',
            field=models.CharField(default='off', max_length=3),
        ),
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
