# Generated by Django 4.1.5 on 2023-06-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_baza_ogloszen_ulubione_alter_baza_ogloszen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='ulubione',
            field=models.CharField(blank=True, default='off', max_length=3, null=True),
        ),
    ]
