# Generated by Django 4.1.5 on 2023-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_alter_baza_ogloszen_ulubione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='foto',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
